# Header
title: WHITE
description: "Simple, concise blog theme for Hexo."
menu:
  Home: /
  Tags: /tags
  About: /about
  Rss: /atom.xml

# Rss
rss: atom.xml

# Copyright
copyright:
  name: helbing
  url: https://github.com/helbing

# Favicon
favicon: /favicon.png

# Social account
social:
  github:
    url: https://github.com/helbing
    icon: "fab fa-github"
  mail:
    url: mailto:helbingxxx@gmail.com
    icon: "fas fa-at"

# Disqus
disqus:
  enable: true
  shortname:
